dist: xenial
language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
- pip install .
script:
- pylint --rcfile=.pylintrc its
- pytest
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: L7gKPARApWnhANZBpW/Ya+fOcWSpc8dLJhCCU6eZTC5fOGi1As02zOkl99U1/SKER9skiVxiGjSMGbjbibJ25GX9S3vrOeJFaiHy+6lskNGshT4Ow2oXfeHmc7qUxe9xXUDEhTfW2zWWH/gMPRTmZdGGkKgkuNVOWBXg/j1BbtykQDfCWJS0YvlZugLvpCBFHKcn5CJG45/vQoJHD0Y0RMwErAeb8UCw/+4syS0c1dEjYm7SXShpbyLPefmgUrAuge8/fRU6ToVrdX6vry+Ubp5jk/020XnJB0mVhIOlbwVSZq+8FOuid6H3UpOLx/jPu3F4W8qE0A6TID0bjjYaR5Pru/aZkEYfnjsa/6Sd1i/+pp8GNrTHdlNtTo+O3XaHZJ3gY0D79cJUfV/BgGKui7aLv8lDGhiXGRE2JnFgmf63/cPjw+5so+HbSbBaQP9URXOnOJNfwVRf/TxCnhI1SCGrSFXihErHQ9I9h9s9zAiJpJ1HD3h+tpIPUtXLfeyS5FWFup1drd71rTaEp+jhlMx7fZ6ItEYCgUnfrIVeDJaG3uA5ltgaeGQN01JblNGJ+36r0F7LYe4vuigFmHGFnu7eiw6oe7DpK5tVynSjRJbtu/XrHgbC9i/7Zpjwftn9RPZjjPWsUanu6gMsqbjRtop7ZgSgWIqkbsx8ZRAOBEs=
  skip_existing: true
  on:
    tags: true
